- name: Add roboshop user 
  ansible.builtin.user:
    name: "{{ app_user }}"

- name: Remove the defult content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create defult content
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download front end zip file 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
