- name: disable nodejs
  ansible.builtin.shell: dnf module disable nodejs -y

- name: enable 18 version nodejs
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installled

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include task list in play
  ansible.builtin.import_tasks:
    file: systemd_setup.yml