# func_print_head copy mongoDB repo file
# cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
# func_stat_check $?
# func_print_head install mongodb shell 
# dnf install mongodb-org-shell -y &>>$log_file
# func_stat_check $?
# func_print_head Load master data of list of products 
# mongo --host mongodb-dev.cloudlife.site </app/schema/${component}.js 
# func_stat_check $?

- name: copy mongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: schema_setup = "mongo"


- name: install mongodb shell
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: installed
  when: schema_setup = "mongo"

- name: Load master data of list of products
  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region="us-east-1") }} </app/schema/{{component}}.js
  when: schema_setup = "mongo"