- name: load mongoDB schema
  block:
    - name: copy mongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb shell
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: installed

    - name: Load master data of list of products
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region="us-east-1") }} </app/schema/{{component}}.js
  when: schema_setup = "mongo"
